on:
 - push
 - pr
jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: https://code.forgejo.org/actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always
